name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test application
      run: |
        python -m unittest discover -s tests

  docker-build:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t simple-docker-webapp .

    - name: Run Docker container
      run: |
        docker run -d -p 11000:11000 --name simple-docker-webapp simple-docker-webapp

    - name: Test Dockerized app
      run: |
        sleep 5 # wait for container to start
        curl -f http://localhost:11000/hello

    - name: Stop and clean up Docker container
      run: |
        docker stop simple-docker-webapp
        docker rm simple-docker-webapp

  docker-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: |
        docker build -t simple-docker-webapp .

    - name: Run Docker container
      run: |
        docker run -d -p 11000:11000 --name simple-docker-webapp simple-docker-webapp

