name: Runner Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  docker-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Stop and clean up Docker, then build and run
      run: 
        ls -laR
        pwd
        sudo -g docker run.sh


