name: Runner Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  docker-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Stop and clean up Docker, then build and run
      run: 
        /bin/bash ./run.sh


